#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build
  - git add .
  - git commit -m "Travis CI build."
  - git push origin master

deploy:  
  provider: azure_web_apps
  site: learnwild
  skip_cleanup: false
  verbose: true
  file: "dist/"
  on:
    branch: master
  
after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change