#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  # - git config --global user.email "jerome.jourdon@gmail.com"
  # - git config --global user.name "ultrarunner"
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  #- git remote add origin https://$GH_TOKEN@github.com/ultrarunner/learn-wild.git/  
  #- git add .
  #- git commit -m "Travis CI build."
  #- git push origin master

#deploy:  
#  provider: azure_web_apps
#  site: learnwild
#  skip_cleanup: false
#  verbose: true
#  file: "dist/"
#  on:
#    branch: master
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

#env:
#  global:
#    -secure: "CbvwcSz2i5e0JFknjwhqFE0QEsIdj9Vzk3Hme7zVuOjcW8h5oUBayd4i7i+S/0yWdMJ/ia2bmTC8qPpRtfozTKL1bUlBVUxiYrqEHoA92S9tT+1ArCRPVR/pi35dKcwxCuXLwlOBXZjtzSO0RliIgpt53FmVdewcsBZ1qo4JJrrQZWu3h11AshlmgMCm7GtCSpAwdPKuCMBj7llh2iZ3C/t9Wfl53ydUhXpkwSO3eaIr81l3lzHzoTCeyQuSaGT/a4aYR/cZOAcfLnraRBFxh/jM2G2tZT0bDCiliJG31DCylWMoCXOc6ExI8IxI7yXhIgArGnPBxdXOJbt8R52y+LWN+25xdYrTVXHbtTEI9WXwrrQpGPgKEhOCTbQM01DwClq095MdSx/B4WK+LfA97gz9dUlAzVihE/GLxRk5HINR7LrQkL267YLqhYOQlN4yeaoGZM4IDEoFgPG15sikTpuiGhw9nN0u7WqUkcLTvHVXbBp1Ai7oh52woCrNFJn6PR71ZytBGgPf+qEvoiAujr7MWYwJVJrJPT/I9u7z4sFjuw8QT5yx6jYOvkM5aw2Gk6LMW64d/VWCwMlXcptMJbRseLM129YIThbWaGum4xCQsWbsOGH9c4q50RHr57nyk8K7hXDdIZxZ6Wow7QyjSfGJyXTlBv6ZzfiDOheN0lg="

notifications:
  email:
    on_failure: change
    on_success: change