#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    #- master
    - dev

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - test $TRAVIS_BRANCH == "dev" && ng build
  #- test $TRAVIS_BRANCH = "master" && ng build -prod

after_success:
  #- firebase deploy --token $FIREBASE_TOKEN --project dev
  - test $TRAVIS_BRANCH == "dev" && firebase deploy --token $FIREBASE_TOKEN --project dev
  #- test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN --project prod

notifications:
  email:
    on_failure: change
    on_success: change 